# -*- coding: utf-8 -*-
"""sentimiento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lcIb-FuFMSV2BFE5oWu7xCRsWeRUQpC

**Analisis de Sentimiento**
"""

# 1. Leer el archivo CSV
ruta_archivo = "/content/drive/MyDrive/UBA_Inteligencia_Artificial/TP FIUBA IA/TP FINAL Analisis Sentimiento Call Center/transcripciones.csv"
df = pd.read_csv(ruta_archivo)

# 2. Función básica de análisis de sentimiento basada en keywords (puede reemplazarse con modelo NLP)
def clasificar_sentimiento(texto):
    if pd.isna(texto):
        return "Sin transcripción"

    texto = texto.lower()

    if "quiero hablar con un supervisor" in texto or "me quejo" in texto or "esto es un desastre" in texto:
        return "Escalar a un supervisor"
    elif any(palabra in texto for palabra in ["no me gustó", "pésimo", "mala atención", "reclamo", "no resolvieron"]):
        return "Mala atención"
    elif any(palabra in texto for palabra in ["está bien", "más o menos", "normal", "ok"]):
        return "Atención neutra"
    elif any(palabra in texto for palabra in ["gracias", "muy buena atención", "excelente", "me atendieron bien"]):
        return "Buena atención"
    else:
        return "Atención neutra"  # por defecto

# 3. Aplicar análisis de sentimiento
df['sentimiento'] = df['transcripcion'].apply(clasificar_sentimiento)

# 4. Mostrar muestra
print(df[['ID', 'uniqueid', 'duracion_segundos', 'transcripcion', 'sentimiento']].head())

# 5. Guardar el archivo actualizado
df.to_csv(ruta_archivo, index=False)
print("✅ Archivo actualizado con análisis de sentimiento guardado.")